name: Deploy MkDocs to GitHub Pages
env:
  # PAT を環境変数ではなく、デプロイアクションの with で直接使用します
  GH_PAT: ${{ secrets.GH_PAGES_PAT }}
on:
  push:
    branches:
      - main  # wiki-page の main ブランチに push したときに実行

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout wiki-page repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocs-git-revision-date-localized-plugin

      - name: Build MkDocs site
        run: |
          mkdocs build --site-dir site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 
        with:
          # PAT を personal_token として with パラメータに渡し、デプロイを行います
          personal_token: ${{ secrets.GH_PAGES_PAT }}
          # ビルド結果のディレクトリ
          publish_dir: ./site
          # デプロイ先のリポジトリ名
          external_repository: Sofia-Luceat-Project/Sofia-Luceat-Project.github.io
          # デプロイ先のブランチ名 (通常 main もしくは gh-pages)
          publish_branch: main
